# Example Docker Compose file for our 2 application
version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    volumes:
      - mssqldata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sample_123
    ports:
      - 1433:1433
    networks:
      - my_network
  click_counter_api:
    build: click_counter_api
    environment: 
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=CountsDb;uid=SA;Password=Sample_123;
    ports:
      - 5010:5000
    depends_on:
      - sqlserver
    networks:
      - my_network
  click_counter_web:
    build: click_counter_web
    environment: 
      - REACT_APP_CLICK_COUNTER_API_URL = http://click_counter_api:5010
      - REACT_APP_COUNT_ENDPOINT = count
    ports:
      - 3010:3000
    networks:
      - my_network
volumes:
  mssqldata:
networks:
  my_network:
    