kind: Service
apiVersion: v1
metadata:
  name: hello-world-web-service
spec:
  selector:
    app: hello-world-web-pod
  ports: 
    - port: 5010
      targetPort: 5000
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world-web-deployment
spec:
  selector:
    matchLabels:
      app: hello-world-web-pod
  template:
    metadata:
      labels:
        app: hello-world-web-pod
    spec:
      containers:
        - name: hello-world-web-container
          image: kubernetes-hello-world:v0.1
          ports:
          - containerPort: 5000
---